services:
  postgres:
    image: vulhub/postgres:10.7
    container_name: postgres.euxcorp.com
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      public_net:
        ipv4_address: 172.16.10.70

  attacker:
    image: metasploitframework/metasploit-framework:latest
    container_name: attacker
    networks:
      public_net:
        ipv4_address: 172.16.10.20
    command: ["sleep", "infinity"]

  apache:
    image: vulhub/unomi:1.5.1
    container_name: apache.euxcorp.com
    ports:
      - "9443:9443"
      - "8181:8181"
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=apache-elasticsearch:9200
    depends_on:
      - apache-elasticsearch
    networks:
      private_net:
        ipv4_address: 10.1.0.18

  apache-elasticsearch:
    image: elasticsearch:7.9.3
    container_name: apache-elasticsearch.euxcorp.com
    environment:
      - cluster.name=contextElasticSearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    networks:
      private_net:
        ipv4_address: 10.1.0.19

  ftp.euxcorp.com:
    image: clintmint/vsftpd-2.3.4:1.0
    container_name: ftp.euxcorp.com
    networks:
      public_net:
        ipv4_address: 172.16.10.30
      private_net:
        ipv4_address: 10.1.0.11
    command: sh -c "start-vsftpd && tail -f /dev/null"

  public.euxcorp.com:
    image: cowrie/cowrie
    container_name: public.euxcorp.com
    networks:
      public_net:
        ipv4_address: 172.16.10.40
    ports:
      - "2222:2222"
    environment:
      COWRIE_USER: admin
      COWRIE_PASS: admin

  access.euxcorp.com:
    image: rastasheep/ubuntu-sshd:latest
    container_name: access.euxcorp.com
    networks:
      private_net:
        ipv4_address: 10.1.0.13
    environment:
      - SSH_PASSWORD=password
    command: /usr/sbin/sshd -D
    expose:
      - "22"

  attacker-private:
    image: metasploitframework/metasploit-framework:latest
    container_name: attacker-private
    networks:
      private_net:
        ipv4_address: 10.1.0.15
    command: ["sleep", "infinity"]

  mysql.euxcorp.com:
    image: vulhub/mysql:5.5.23
    container_name: mysql.euxcorp.com
    networks:
      public_net:
        ipv4_address: 172.16.10.60
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  web.euxcorp.com:
    image: vulhub/uwsgi-php:2.0.16
    container_name: web.euxcorp.com
    networks:
      private_net:
        ipv4_address: 10.1.0.17
    expose:
      - "8080"

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
